### PR TITLE
Internal API metrics

### LINKED ISSUE #63: Make trim to all the geocoder client inputs
We have to trim all the inputs to avoid empty searches due to empty spaces in the queries.

// @rafatower @jsanz

### PR DESCRIPTION
**Pull request by ethervoid**
This PR closes #63 

- [x] Refactor of the extension to rename it as `cdb_dataservices`
- [x] Refactor to move all the interfaces generator's stuff to the client
- [x] Trim all the inputs in order to avoid problems with spaces (#63)
- [x] Add metrics storage for all the internal geocoder functions

### CODE REVIEW

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
@rafatower all is done, i have to test it in staging. could you please check it out. thx

**Comment by ethervoid** [comment]
retest this please

**Comment by rafatower** [comment]
In general I'm ok with the changes but I just want to make sure you have a plan for the migration.

**Comment by ethervoid** [comment]
Yes, i put it in the worklog!

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
retest this please

**Pull request merged**
